name: EvaDecoration
version: '${version}'
main: kr.kua.evadecoration.EvaDecoration
api-version: 1.20
authors: [ Kua ]
website: https://evatuna.fish
depend: [MagicCosmetics, MythicMobs, ProtocolLib, NametagEdit, Vault, PlaceholderAPI]

commands:
  evadecoration:
    aliases:
      - ed
    description: 데코레이션 GUI를 엽니다.